const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/common/core.js'),U=require('../src/common/shared.js'),P=require('../src/common/preferences.js');
function send(a,type,value){return a.dispatch({type,value});}
function change(a){const s=a.snapshot();if('max'in s)return {type:'choose',value:20};if('category'in s)return {type:'category',value:'length'};return {type:'dimension',value:'volume'};}
for(const raw of ['', '{}','null','oops','{"max":8,"category":"bad","dimension":"bad"}'])test('bad storage '+raw,()=>{const a=C.createApp();const before=a.snapshot().preferences;const p=P.connect({get:o=>o.success(raw),set:o=>o.fail()},'test',a,()=>{});assert.deepEqual(a.snapshot().preferences,before);p.dispatch(change(a));assert.ok(a.snapshot().elements.length);});
test('absent, thrown and failed storage never blocks utility',()=>{for(const storage of [null,{}, {get:()=>{throw Error('read')},set:()=>{throw Error('write')}}, {get:o=>o.fail(),set:o=>o.fail()}]){const a=C.createApp(),p=P.connect(storage,'test',a,()=>{});p.dispatch(change(a));assert.ok(a.snapshot().elements.length);p.destroy();}});
test('late reads, writes only on changes, serialization and destruction',()=>{const a=C.createApp();let read,writes=[],callbacks=[];const p=P.connect({get:o=>{read=o.success},set:o=>{writes.push(o.value);callbacks.push(o.success)}},'test',a,()=>{});const original=a.snapshot().preferences;p.dispatch(change(a));const changed=a.snapshot().preferences;assert.equal(writes.length,1);read(JSON.stringify(original));assert.deepEqual(a.snapshot().preferences,changed);p.dispatch({type:'back'});assert.equal(writes.length,1);callbacks.shift()();p.destroy();read(JSON.stringify(original));assert.deepEqual(a.snapshot().preferences,changed);});
test('tiny numbers and negative zero format honestly; strict editor input',()=>{for(const n of [1e-100,1e-12,1e12,1e100]){const s=U.format(n);assert.ok(Number(s)>0);assert.ok(s.length<=12);}assert.equal(U.format(-0),'0');for(const s of ['', '-', '.', '1abc','1e3','Infinity'])assert.throws(()=>U.decimal(s));assert.equal(U.edit('2','DEL',false,false),'');});
function check(a){const s=a.snapshot(),ids=new Set();for(const e of s.elements){assert.ok(!ids.has(e.id));ids.add(e.id);assert.ok(e.x>=0&&e.y>=68&&e.x+e.w<=212&&e.y+e.h<=460,JSON.stringify(e));assert.ok(!/NaN|Infinity/.test(e.text));if(e.action==='key'){assert.ok(e.w>=44&&e.h>=40);}if(e.action){assert.ok(e.h>=36,'Small hit target: '+e.text);for(const [x,y]of [[e.x+3,e.y+3],[e.x+e.w-3,e.y+3],[e.x+3,e.y+e.h-3],[e.x+e.w-3,e.y+e.h-3]]){const cy=y<106?106:y>414?414:y;assert.ok((x-106)**2+(y-cy)**2<=106**2,JSON.stringify(e));}}}const buttons=s.elements.filter(e=>e.action);for(let i=0;i<buttons.length;i++)for(let j=i+1;j<buttons.length;j++){const a=buttons[i],b=buttons[j];assert.ok(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'overlapping buttons '+a.text+' / '+b.text);}return s;}
test('all native/preview view geometries and navigation pages fit capsule',()=>{const a=C.createApp();check(a);if('max'in a.snapshot()){send(a,'select');check(a);for(const n of C.MAXIMA){send(a,'choose',n);send(a,'roll');check(a);send(a,'select');check(a);}}else if('category'in a.snapshot()){send(a,'categories');check(a);send(a,'next');check(a);for(const c of C.categories){send(a,'category',c.id);check(a);send(a,'units');check(a);send(a,'next');check(a);send(a,'back');for(const u of c.units){send(a,'unit',u[0]);check(a);send(a,'next');check(a);send(a,'edit');check(a);if(u[0]==='in'){send(a,'mode');check(a);for(const n of ['0','1','2']){send(a,'part',n);check(a);send(a,'cancel');}send(a,'cancel');}else send(a,'cancel');}}}else{send(a,'dimensions');check(a);for(const dim of Object.keys(C.dimensions)){send(a,'dimension',dim);check(a);for(const id of ['Aprice','Aquantity','Bprice','Bquantity']){send(a,'edit',id);check(a);if(id.endsWith('quantity')){send(a,'mode');check(a);send(a,'unit',C.dimensions[dim].units[0][0]);}send(a,'key','AC');send(a,'key','1');send(a,'done');}send(a,'compare');check(a);send(a,'details');check(a);send(a,'reset');check(a);send(a,'confirm');}send(a,'dimension','mass');send(a,'edit','Aquantity');send(a,'key','1');send(a,'done');send(a,'dimension','volume');check(a);}});
test('pending preference writes coalesce and storage errors release the queue',()=>{let state={value:0},calls=[];const app={snapshot:()=>({preferences:{value:state.value}}),dispatch:a=>{state.value=a.value}};const connection=P.connect({get:()=>{},set:o=>calls.push(o)},'test',app,()=>{});connection.dispatch({value:1});connection.dispatch({value:2});connection.dispatch({value:3});assert.equal(calls.length,1);calls[0].fail();assert.equal(calls.length,2);assert.equal(JSON.parse(calls[1].value).value,3);calls[1].success();connection.dispatch({value:3});assert.equal(calls.length,2);});
