const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/common/core.js');
function near(a,b){assert.ok(Math.abs(a-b)<=1e-10*Math.max(1,Math.abs(b)),`${a} != ${b}`);}
function input(dimension,pa,qa,ua,pb,qb,ub){return {dimension,a:{price:pa,quantity:qa,unit:ua},b:{price:pb,quantity:qb,unit:ub}};}
const fixtures=[
 [input('mass',4,500,'g',5.5,750,'g'),'B',8,7.333333333333,8.33333333333],
 [input('mass',3,250,'g',10,1,'kg'),'B',12,10,16.6666666667],
 [input('mass',4,16,'oz',8,2,'lb'),'equal',8.818490487395,8.818490487395,0],
 [input('volume',3,750,'ml',5,2,'l'),'B',4,2.5,37.5],
 [input('count',6,12,'items',8,20,'items'),'B',.5,.4,20],
 [input('mass',0,500,'g',1,500,'g'),'A',0,2,100],
 [input('mass',0,500,'g',0,500,'g'),'equal',0,0,0]
];
for(const [i,w,a,b,s]of fixtures)test(JSON.stringify(i),()=>{const r=C.compare(i);assert.equal(r.winner,w);near(r.rateA,a);near(r.rateB,b);near(r.saving,s);});
test('cheaper unit price is separate from lower cash price',()=>assert.equal(C.compare(fixtures[0][0]).lowerTotal,'A'));
test('US fluid ounces and mass versus volume validation',()=>{assert.equal(C.compare(input('volume',1,1,'usfloz',1,29.5735295625,'ml')).winner,'equal');assert.throws(()=>C.compare(input('mass',1,1,'usfloz',1,1,'g')));});
test('swapping, scaling both prices, scaling one package and basis invariant',()=>{for(const [i]of fixtures){const r=C.compare(i),swap=C.compare({dimension:i.dimension,a:i.b,b:i.a});assert.equal(swap.winner,r.winner==='equal'?'equal':r.winner==='A'?'B':'A');near(swap.saving,r.saving);for(const scale of [.0001,3,1e8]){let j=JSON.parse(JSON.stringify(i));j.a.price*=scale;j.b.price*=scale;assert.equal(C.compare(j).winner,r.winner);near(C.compare(j).saving,r.saving);j=JSON.parse(JSON.stringify(i));j.a.price*=3;j.a.quantity*=3;near(C.compare(j).unitPriceA,r.unitPriceA);}for(const basis of C.dimensions[i.dimension].bases)assert.equal(C.compare(i,basis[0]).winner,r.winner);}});
test('invalid input never becomes a free package or zero quantity',()=>{for(const [key,bad]of [['price',-1],['price',null],['price',''],['price',NaN],['quantity',0],['quantity',-1],['quantity',null],['quantity',Infinity],['unit','ml']]){const i=input('mass',1,1,'g',2,1,'g');i.a[key]=bad;assert.throws(()=>C.compare(i));}assert.throws(()=>C.compare(input('count',1,1.5,'items',2,2,'items')));assert.throws(()=>C.compare(input('x',1,1,'g',2,1,'g')));});
test('near ties and very small/large positive values use relative tolerance',()=>{for(const scale of [1e-100,1e-12,1,1e12,1e100]){const r=C.compare(input('mass',scale,1,'g',scale*(1+1e-8),1,'g'));assert.equal(r.winner,'A');assert.ok(r.saving>0);assert.equal(C.compare(input('mass',scale,1,'g',scale*(1+1e-13),1,'g')).winner,'equal');}});
function send(a,type,value){return a.dispatch({type,value});}
function field(a,id,value,unit){send(a,'edit',id);send(a,'key','AC');for(const k of value)send(a,'key',k);if(unit){send(a,'mode');send(a,'unit',unit);}send(a,'done');}
test('full comparison, edit preservation, cancel, detail/basis and reset confirmation',()=>{const a=C.createApp();field(a,'Aprice','4');field(a,'Aquantity','500');field(a,'Bprice','5.5');field(a,'Bquantity','750');send(a,'compare');assert.equal(a.snapshot().result.winner,'B');send(a,'basis');assert.equal(a.snapshot().result.winner,'B');send(a,'details');send(a,'overview');const before=a.snapshot().b;send(a,'edit','Aprice');send(a,'key','AC');send(a,'key','9');send(a,'cancel');assert.equal(a.snapshot().a.price,4);assert.deepEqual(a.snapshot().b,before);send(a,'reset');send(a,'cancel');assert.equal(a.snapshot().a.price,4);send(a,'reset');send(a,'confirm');assert.equal(a.snapshot().a.price,null);assert.equal(a.snapshot().b.quantity,null);});
test('dimension change clears quantities/units after confirmation and retains prices',()=>{const a=C.createApp();field(a,'Aprice','4');field(a,'Aquantity','500');send(a,'dimensions');send(a,'dimension','volume');assert.equal(a.snapshot().screen,'confirmDimension');send(a,'cancel');assert.equal(a.snapshot().a.quantity,500);send(a,'dimension','volume');send(a,'confirm');assert.equal(a.snapshot().a.quantity,null);assert.equal(a.snapshot().a.unit,null);assert.equal(a.snapshot().a.price,4);field(a,'Aquantity','1','l');assert.equal(a.snapshot().a.unit,'l');});
test('empty, zero and fractional item entries recover',()=>{const a=C.createApp();send(a,'edit','Aprice');send(a,'done');assert.equal(a.snapshot().screen,'editor');send(a,'key','0');send(a,'done');assert.equal(a.snapshot().a.price,0);send(a,'edit','Aquantity');send(a,'key','0');send(a,'done');assert.equal(a.snapshot().screen,'editor');send(a,'key','DEL');assert.equal(a.snapshot().draft,'');send(a,'key','1');send(a,'done');assert.equal(a.snapshot().a.quantity,1);});
test('preferences restore no prices and cannot overwrite user state',()=>{const a=C.createApp();send(a,'restore',{dimension:'volume',bases:{volume:'100ml'},a:{price:50}});assert.equal(a.snapshot().dimension,'volume');assert.equal(a.snapshot().a.price,null);field(a,'Aprice','3');send(a,'restore',{dimension:'count'});assert.equal(a.snapshot().dimension,'volume');});
test('near-100% displayed savings are approximate for two positive prices',()=>{const a=C.createApp();field(a,'Aprice','.00000000001');field(a,'Aquantity','1');field(a,'Bprice','999999999999');field(a,'Bquantity','1');send(a,'compare');assert.ok(a.snapshot().elements.some(e=>e.text.startsWith('~100%')));send(a,'overview');field(a,'Aprice','0');send(a,'compare');assert.ok(a.snapshot().elements.some(e=>e.text.startsWith('100%')));});
