// Generates a fully offline preview of the SAME state machine and screen geometry.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),m=require('../src/manifest.json');
const scripts=['shared','preferences','core'].map(n=>fs.readFileSync(path.join(root,'src/common',n+'.js'),'utf8')).join('\n');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${m.name} — preview</title><link rel="icon" href="data:,">
<style>*{box-sizing:border-box}body{margin:0;background:#0d1218;color:#f5f7f8;font-family:Arial,sans-serif;padding:24px;display:flex;justify-content:center;gap:40px;align-items:center;min-height:100vh}.screen{position:relative;width:212px;height:520px;border-radius:106px;overflow:hidden;background:#000;flex-shrink:0;box-shadow:0 0 0 8px #232a30}.element{position:absolute;margin:0;padding:2px;border:0;display:flex;align-items:center;justify-content:center;text-align:center;font-family:Arial,sans-serif;font-weight:bold;line-height:1.15;white-space:pre-line;overflow:hidden}.element span{max-width:100%;overflow-wrap:normal}button{cursor:pointer;touch-action:manipulation}button:active{filter:brightness(1.3)}button:focus-visible{outline:2px solid white;outline-offset:-3px}aside{max-width:340px;line-height:1.6;color:#a4b3b8}h1{color:#f5f7f8;font-size:28px}aside button{padding:10px;background:#232a30;color:#f5f7f8;border:1px solid #70dbc5;border-radius:8px}@media(max-width:650px){body{flex-direction:column;gap:24px}}
</style><div id="screen" class="screen" aria-label="${m.name}: 212 by 520 band preview"></div><aside><h1>${m.name}</h1><p>Offline · 0.1.0 · Xiaomi Smart Band 10</p><p>Tap the controls. Digits and Backspace work in editors; Enter commits, Escape cancels. Focused buttons also support Enter and Space.</p><button id="zoom" type="button">Enlarge 2×</button><p>This preview shares the native app’s engine, state and layout. It is not a Vela emulator. Physical-band behavior is unverified.</p></aside>
<script>${scripts}</script><script>
const app=WristCore.createApp();window.wristApp=app;const screen=document.getElementById('screen');
function render(){const focused=document.activeElement;const focusKey=focused&&focused.dataset?focused.dataset.action+'|'+focused.dataset.value:'';screen.replaceChildren();const s=app.snapshot();screen.dataset.screen=s.screen;s.elements.forEach(e=>{const el=document.createElement(e.action?'button':'div');el.className='element';el.dataset.action=e.action;el.dataset.value=e.value;el.dataset.id=e.id;if(e.action)el.type='button';el.style.cssText='left:'+e.x+'px;top:'+e.y+'px;width:'+e.w+'px;height:'+e.h+'px;background:'+e.background+';color:'+e.color+';font-size:'+e.font+'px;border-radius:'+e.radius+'px';const span=document.createElement('span');span.textContent=e.text;el.appendChild(span);if(e.action)el.addEventListener('click',()=>connection.dispatch({type:e.action,value:e.value}));screen.appendChild(el);if(e.action&&e.action+'|'+e.value===focusKey)el.focus({preventScroll:true});});}
const adapter={get:o=>{try{o.success(localStorage.getItem('${m.package}.preferences-v1')||'');}catch(e){if(o.fail)o.fail();}},set:o=>{try{localStorage.setItem('${m.package}.preferences-v1',o.value);o.success();}catch(e){o.fail();}}};
const connection=WristPreferences.connect(adapter,'preferences-v1',app,render);window.wristDispatch=a=>connection.dispatch(a);render();
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if((e.key==='Enter'||e.key===' ')&&e.target.tagName==='BUTTON')return;const s=app.snapshot();let action=null;if(e.key==='Escape')action=s.elements.find(x=>x.action==='cancel'||x.action==='back');else if(e.key==='Enter')action=s.elements.find(x=>x.action==='done'||x.action==='roll');else if(e.key===' '&&s.screen==='home')action=s.elements.find(x=>x.action==='roll');else{const key=e.key==='Backspace'?'DEL':e.key==='Delete'?'AC':e.key;action=s.elements.find(x=>x.action==='key'&&x.value===key);}if(action){e.preventDefault();connection.dispatch({type:action.action,value:action.value});}});
let enlarged=false;document.getElementById('zoom').addEventListener('click',()=>{enlarged=!enlarged;screen.style.zoom=enlarged?2:1;document.getElementById('zoom').textContent=enlarged?'Native size':'Enlarge 2×';});
</script></html>`;
fs.writeFileSync(path.join(root,'preview.html'),html);
fs.writeFileSync(path.join(__dirname,'layout.json'),JSON.stringify({width:212,height:520,safeTop:68,safeBottom:460,keypad:{left:12,width:60,height:50,columnStep:64,top:242,rowStep:56}},null,2)+'\n');
console.log('Generated '+path.join(root,'preview.html'));
